// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hednilzhruqcmmslowfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZG5pbHpocnVxY21tc2xvd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDIyMTIsImV4cCI6MjA2NDM3ODIxMn0.38cS2ciQTEPrA9hXd06Q6Iays-1WEewZPR7BEWokwXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);